---
title: "Irregular respose times"
author: "Megan Waller and Dan Yurovsky"
date: '`r Sys.Date()`'
output:
  html_document:
  highlight: tango
theme: sandstone
code_folding: show
toc: false
toc_float: false
---
  
```{r libraries}
library(tidyverse)
library(here)
library(ggthemes)
library(glue)
library(janitor)
library(fuzzyjoin)

theme_set(theme_few(base_size = 12))

```

```{r helpers}
process_age <- function(age) {
  age_list <- sub("\\['P", "", age) %>%
    sub("D'\\]", "", .) %>%
    str_split(., "[:alpha:]") %>%
    unlist()
  
  processed_age = as.numeric(age_list[1]) * 365.25 + as.numeric(age_list[2]) * 30.5
  
  if(age_list[3] != "']") {
    processed_age = processed_age + as.numeric(age_list[3])
  }
  
  return(processed_age)
}

process_errors <- function(corpus) {
  utts <- read_csv(here(glue("corpus/data/{corpus}_utterance_data.csv"))) %>%
    filter(response_time != "s1 or s2 media info not available") %>%
    mutate(error = as.logical(error),
           response_time = as.numeric(response_time) * 1000) %>%
    group_by(source_file) %>%
    mutate(age = process_age(age)) 
  

  child_data <- utts %>%
    filter(speaker == "CHI" & responder != "CHI" & (past_tense | plural ))

  child_errors <- child_data %>%
    filter(error)

  if(! "start_time" %in% names(child_errors)) {
    child_errors <- child_errors %>%
      mutate(start_time = 0)
  } else {
    child_errors <- child_errors %>%
      mutate(start_time = as.numeric(start_time))
  }
  
  child_errors %>%
    select(source_file, age, utterance, responder, response, start_time, response_time) %>%
    mutate(overreg_past = "", overreg_plural = "",
           start_time = start_time / 60) %>%
    rename(start_time_minutes = start_time) %>%
    write_csv(here(glue("corpus/tocode_data/experimental/{corpus}_tocode.csv")))
}

```

```{r process-errors, warning = FALSE, eval = FALSE}
process_errors("braunwald")
process_errors("sachs")
process_errors("ben")
process_errors("emily")
process_errors("emma")
process_errors("jillian")
process_errors("matt")
process_errors("roman")
```

```{r read-errors}
read_errors <- function(corpus) {
  coded <- read_csv(here(glue("corpus/coded_data/{corpus}_coded.csv")))
  coded <- coded %>% 
    filter(overreg_past == TRUE | overreg_plural == TRUE)
  return(coded)
}

corpus_list <- c("braunwald", "sachs", "ben", "emily", "emma", 
             "jillian", "matt", "roman")

corpus_errors <- map_dfr(corpus_list, read_errors, .id = "corpus") %>%
  mutate(corpus = factor(corpus, labels = corpus_list),
         age_years = age / 365.25,
         length = str_count(utterance, " ") + 1)
```

```{r read-elan}
read_elan <- function(file, directory = here("corpus/elan_coded")) {
  read_delim(glue("{directory}/{file}"), "\t") %>%
    clean_names() %>%
    mutate(person = if_else(is.na(child_error_utterance) , "parent", "child")) %>%
    select(-child_error_utterance, -parent_error_response) %>%
    arrange(begin_time_msec) %>%
    group_by(person) %>%
    mutate(utt_num = 1:n()) %>%
    group_by(utt_num) %>%
    mutate(response_time = last(begin_time_msec) - first(end_time_msec)) %>%
    ungroup() %>%
    filter(person == "child") %>%
    mutate(corpus_file = file) %>%
    select(corpus_file, response_time, utt_num)
}
```

```{r load_response_times}
elan_files <- list.files(here("corpus/elan_coded/"))

elan_response_times <- map_dfr(elan_files, read_elan) %>%
  separate(corpus_file, into = c("corpus", "file"), sep = "_") %>%
  mutate(file = sub(".txt", "", file))

fixed_file_corpus_errors <- corpus_errors %>%
  rowwise() %>%
  mutate(source_file = str_split(source_file, "/") %>% unlist() %>% last,
         source_file = sub(".xml", "", source_file)) %>%
  rename(file = source_file) %>%
  group_by(corpus, file) %>%
  mutate(utt_num = 1:n())

timed_errors <- fixed_file_corpus_errors %>%
  filter(elan_coded) %>%
  select(-response_time) %>%
  left_join(elan_response_times, by = c("corpus", "file", "utt_num")) %>%
  bind_rows(filter(fixed_file_corpus_errors, is.na(elan_coded))) %>%
  filter(responder != "SIS")
```

```{r}
ggplot(timed_errors, aes(x = response_time)) + 
  geom_histogram()
```

```{r make-control-utts}
make_control_utts <- function(errors_df) {
  corpora <- pull(errors_df, corpus) %>% unique()
 
  possible_control_utts <- function(corpus) {
    read_csv(here(glue("corpus/data/{corpus}_utterance_data.csv"))) %>%
      #missing form sachs
      filter(response_time != "s1 or s2 media info not available") %>% 
      mutate(response_time = as.numeric(response_time),
             utterance_time = as.numeric(utterance_time)) %>%
      mutate(error = as.logical(error)) %>%
      filter(!error, speaker == "CHI", responder != "CHI") %>%
      mutate(length = str_count(utterance, " ") + 1) %>%
      filter(length >= 1) %>%
      group_by(source_file) %>%
      mutate(age = process_age(age)) %>%
      mutate(age_months = floor(age/30.5)) %>%
      group_by(responder, age_months, length) %>%
      nest() %>%
      mutate(corpus = corpus)
  }
  
  utts <- map_dfr(corpora, possible_control_utts)

  errors <- errors_df %>%
    mutate(age_months = floor(age/30.5)) %>%
    rename("past_tense" = "overreg_past",
           "plural" = "overreg_plural") %>%
    mutate_at(vars(past_tense, plural), as.character) %>%
    fuzzy_left_join(utts, 
                    by = c("corpus", "responder", "age_months", "length"),
                    match_fun = list("corpus" = ~.x == .y,
                                     "responder" = ~.x == .y,
                                     "age_months" = ~abs(.x -.y) <= 10,
                                     "length" = ~abs(.x -.y) <= 10)) %>%
    mutate(diff = abs(age_months.x - age_months.y) + 
             abs(length.x - length.y)) %>%
    group_by(corpus.x, age_months.x, responder.x, utterance, past_tense, plural, length.x,
             response_time) %>%
    unnest() %>%
    mutate(start_time = start_time / 60,
           source_file = str_split(source_file, "/") %>%  unlist() %>% last,
                  source_file = sub(".xml", "", source_file)) %>%
    rename(corpus = corpus.x,
           speaker = speaker,
           responder = responder.x,
           experimental_file = file,
           experimental_utterance = utterance,
           experimental_response = response,
           experimental_start_time_minutes = start_time_minutes,
           experimental_age_years = age_years,
           experimental_age_months = age_months.x,
           experimental_length = length.x,
           experimental_utt_num = utt_num,
           experimental_response_time = response_time,
           experimental_past_tense = past_tense,
           experimental_plural = plural,
           experimental_elan_coded = elan_coded,
           control_file = source_file,
           control_length = length.y,
           control_age = age1,
           control_age_months = age_months.y,
           control_utterance = utterance1,
           control_response = response1,
           control_response_time = response_time1,
           control_past_tense = past_tense1,
           control_plural = plural1,
           control_start_time_minutes = start_time) %>%
  select(-error, -corpus.y, -overlap, -age, -responder.y, -utterance_time)
}  
```

```{r iteratively-sample}
iteratively_sample <- function(utts, diff_n) {
 
  sampled_utts <- utts %>%
    group_by(corpus, experimental_file, experimental_age_months,
             experimental_utterance) %>%
    filter((diff - min(diff)) == diff_n) %>%
    sample_frac(1) %>%
    slice(1:remaining) %>%
    mutate(n = n())
  
  complete_utts <- sampled_utts %>%
    filter(n == remaining) %>%
    select(-n) %>%
    ungroup()
  
  partial_utts <- sampled_utts %>%
    filter(n != remaining) %>%
    mutate(now_remaining = remaining - n) %>%
    ungroup()
  
  non_complete_utts <- utts %>%
    anti_join(complete_utts %>%
                select(corpus, experimental_file, experimental_utt_num),
              by = c("corpus", "experimental_file", 
                     "experimental_utt_num")) %>%
    anti_join(partial_utts %>%
                select(corpus, experimental_file, experimental_utt_num,
                       control_response),
              by = c("corpus", "experimental_file", 
                     "experimental_utt_num", "control_response")) %>%
    left_join(partial_utts %>% select(corpus, experimental_file, 
                                      experimental_utt_num, now_remaining), 
              by = c("corpus", "experimental_file", "experimental_utt_num")) %>%
    mutate(remaining = if_else(is.na(now_remaining), 
                               remaining, now_remaining)) %>%
    select(-now_remaining)
  
  if(nrow(non_complete_utts) == 0)
    return(bind_rows(complete_utts, partial_utts %>% select(-now_remaining)))
  else
    return(bind_rows(complete_utts, partial_utts %>% select(-now_remaining),
                     iteratively_sample(non_complete_utts, diff_n + 1)))
}
```


```{r sample-controls}
SAMPLE_N <- 3
errors <- make_control_utts(timed_errors)

controls <- iteratively_sample(errors %>% mutate(remaining = SAMPLE_N), 0) %>%
  select(-n, -remaining)

write_csv(controls, here("corpus/tocode_data/control/control_timing_full.csv"))

write_csv(controls %>% 
            select(corpus, control_file, control_utterance, control_response, 
                   control_start_time_minutes),
          here("corpus/tocode_data/control/control_timing_tocode.csv"))
```

```{r response-times, eval = FALSE}
ggplot(child_data, aes(x = response_time, color = error))  +
  geom_density()
```

```{r nelson, eval = FALSE, show = FALSE}
process_errors("nelson")
#found no errors

nelson_utts <- read_csv(here(glue("data/nelson_utterance_data.csv"))) %>%
  mutate(error = as.logical(error),
         response_time = as.numeric(response_time)) %>%
  group_by(source_file) %>%
  mutate(age = process_age(age)) 

nerrors <- nelson_utts %>% filter(error == TRUE)

nelson_child_data <- nelson_utts %>%
  filter(speaker == "CHI" & responder != "CHI" & (past_tense | plural ))
nelson_child_errors <- nelson_child_data %>%
    filter(error)
```
