---
title: "Irregular respose times"
author: "Megan Waller and Dan Yurovsky"
date: '`r Sys.Date()`'
output:
  html_document:
  highlight: tango
theme: sandstone
code_folding: show
toc: false
toc_float: false
---
  
```{r libraries}
library(tidyverse)
library(here)
library(ggthemes)
library(glue)

theme_set(theme_few(base_size = 12))

```

```{r helpers}
process_age <- function(age) {
  age_list <- sub("\\['P", "", age) %>%
    sub("D'\\]", "", .) %>%
    str_split(., "[:alpha:]") %>%
    unlist()
  
  processed_age = as.numeric(age_list[1]) * 365.25 + as.numeric(age_list[2]) * 30.5
  
  if(age_list[3] != "']") {
    processed_age = processed_age + as.numeric(age_list[3])
  }
  
  return(processed_age)
}

process_errors <- function(corpus) {
  utts <- read_csv(here(glue("data/{corpus}_utterance_data.csv"))) %>%
    mutate(error = as.logical(error),
           response_time = as.numeric(response_time)) %>%
    group_by(source_file) %>%
    mutate(age = process_age(age)) 

  child_data <- utts %>%
    filter(speaker == "CHI" & responder != "CHI" & (past_tense | plural ))


  child_errors <- child_data %>%
    filter(error)

  child_errors %>%
    select(source_file, age, utterance) %>%
    mutate(overreg_past = "", overreg_plural = "") %>%
    write_csv(here(glue("tocode_data/{corpus}_tocode.csv")))
}

```

```{r braunwald, warning = FALSE}
process_errors("braunwald")
```

```{r read-errors}
read_errors <- function(corpus) {
  coded <- read_csv(here(glue("coded_data/{corpus}_coded.csv")))
  coded <- coded %>% 
    filter(overreg_past == TRUE | overreg_plural == TRUE)
  return(coded)
}
```

```{r braunwald-errors}
braunwald <- read_errors("braunwald")
```

```{r process-errors}
process_errors("sachs")
process_errors("ben")
process_errors("emily")
process_errors("emma")
process_errors("jillian")
process_errors("matt")
process_errors("roman")
```


```{r read-errors}
sachs <- read_errors("sachs") #8 ORs
ben <- read_errors("ben") #3 ORs
emily <- read_errors("emily") #31 ORs
emma <- read_errors("emma") #18 ORs
jillian <- read_errors("jillian") #34 ORs
matt <- read_errors("matt") #4 ORs
roman <- read_errors("roman") #6 ORs
```


```{r nelson}
process_errors("nelson")
#found no errors

nelson_utts <- read_csv(here(glue("data/nelson_utterance_data.csv"))) %>%
  mutate(error = as.logical(error),
         response_time = as.numeric(response_time)) %>%
  group_by(source_file) %>%
  mutate(age = process_age(age)) 

nerrors <- nelson_utts %>% filter(error == TRUE)

nelson_child_data <- nelson_utts %>%
  filter(speaker == "CHI" & responder != "CHI" & (past_tense | plural ))
nelson_child_errors <- nelson_child_data %>%
    filter(error)
```

```{r response-times, eval = FALSE}
ggplot(child_data, aes(x = response_time, color = error))  +
  geom_density()
```
